run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gocritic
    - misspell
    - unconvert
    - unparam
  disable:
    - depguard

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-tags:
      - experimental
      - opinionated
      - performance
      - security

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
