version: "2"

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

issues:
  exclude-rules:
    - linters: [errcheck]
      text: 'Error return value of .*\.Close is not checked'
    - path: _test\.go
      linters: [errcheck]
      text: 'Error return value of .*db\.Exec is not checked'
    - path: src/internal/cli/.*\.go
      linters: [errcheck]
      text: 'Error return value of .*fmt\.Fprint(f|ln)? is not checked'
    - path: src/internal/cli/.*\.go
      linters: [errcheck]
      text: 'Error return value of .*f\.WriteString? is not checked'
