# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: hermem

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: hermem
    main: ./src
    binary: hermem
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildDate={{.Date}}
      - -X main.gitCommit={{.ShortCommit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE*
      - hermem.ini
      - docs/**

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^Merge"

release:
  github:
    owner: pavelveter
    name: hermem
  draft: false
  prerelease: auto
