/** @hermem/sdk — Official TypeScript SDK for the Hermem API. */

export { Client, APIError, type ClientOptions } from "./client";
export type {
  Entity,
  Edge,
  StoreRequest,
  SearchRequest,
  RetrieveRequest,
  IngestRequest,
  EdgeRequest,
  SearchResult,
  ScoreBreakdown,
  RetrievedFact,
  GraphNode,
  RetrievalResult,
  TaskStatusRequest,
  TaskListRequest,
  TaskShowRequest,
  TaskShowResponse,
  TaskDepRequest,
  TaskCreateRequest,
  TaskCreateResponse,
  TaskRollbackRequest,
  TaskRollbackResponse,
  TaskTreeRequest,
  TaskTreeResponse,
  TaskExecutableResponse,
  ContradictionPair,
  ConnectedComponent,
  Community,
  VerifyReport,
  ReEmbedRequest,
  ReEmbedResult,
  TimelineEntry,
  QueryResponse,
  HealthResponse,
  ReadyResponse,
  CheckResult,
  MigStatus,
  SchemaReport,
} from "./types";
